DAI_WEB_URL = 'https://dai.uvigo.gal/'
DAI_INSTAGRAM_URL = 'https://www.instagram.com/dai_uvigo/'
DAI_TWITTER_URL = 'https://twitter.com/dai_uvigo'
DAI_MAIL_URL = 'mailto:delegacion@dai.uvigo.gal'
DAI_WHATSAPP_URL = 'https://wa.me/+34986813656'
